<Gerenciador>:
    Menu:
        name:'menu'
    Tarefas:    
        name: 'tarefas'

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        padding: 100
        spacing: 10
        canvas:
            Color: 
                rgba: 1,1,1,1
            Rectangle:
                size: self.size
                pos: self.pos
                source: './images/menu-wallpaper.jpg'
        Image:
            source: './images/carteira.jpg'
            size_hint_y:None 
            height: 100
        Botao:
            text:'Tarefas'
            on_release: app.root.current = 'tarefas'
        Botao:
            text:'Assistente'
        Botao:
            text:'Sair'
            on_release: root.confirmacao()
            



<Tarefas>:
    BoxLayout:
        orientation: 'vertical'
        ActionBar: 
            ActionView:
                ActionPrevious: 
                    title: 'Tarefas'
                    on_release: app.root.current = 'menu'
                ActionButton:
                    text: 'Sair'
                    on_release: app.stop()
        ScrollView:
            BoxLayout:
                id: box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height  
        BoxLayout:
            size_hint_y:None
            height: 60
            TextInput:
                id: texto
            Button:  
                text:'+'
                size_hint_x:None 
                width: 60
                on_release: root.addWidget()

<Tarefa>
    size_hint_y:None 
    height: 200
    Label:
        id: label
        font_size: 30
    Button:
        size_hint_x: None
        width: 60
        text: 'X'
        on_release: app.root.get_screen('tarefas').ids.box.remove_widget(root)

